language: php
php:
    - 7.2

install:
    - composer install

script:
    - mkdir -p build/logs
    - composer test

after_script:
    - composer require satooshi/php-coveralls
    - php vendor/bin/coveralls
