language: php
php:
    - 5.6
    - 7.0

matrix:
    fast_finish: true

install:
    - composer install

script:
    - mkdir -p build/logs
    - composer test

after_script:
    - php vendor/bin/coveralls

