language: php
php:
    - 7.0
    - 7.1
    - 7.2

matrix:
    fast_finish: true

install:
    - composer install

script:
    - mkdir -p build/logs
    - composer test

after_script:
    - composer require satooshi/php-coveralls
    - php vendor/bin/coveralls
